### ISSUE TITLE
recipientName

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-types-address#3]
@wrygiel : 
I assume `recipientName` will not be used, since this is Erasmus **Without** Paper :-)

**Comment by wrygiel** [comment]
Why? We are, after all, discussing postal addresses. Sure, ultimately we want people to stop using those, but until we achieve that, I think we need that field?

**Comment by kaiqu** [comment]
I was being flippant. What I meant was that there is already a contact-name - do we need the recipientName as well?

**Comment by wrygiel** [comment]
> What I meant was that there is already a contact-name

We don't have a "contact-name" in the address data type. We have one in AbstractContact though, so probably this is what you mean?

When the address is being embedded inside an AbstractContact, then we will indeed have some redundant information, but I'm not really sure if this is bad. We have seen this `recipientName` field in a some XML address formats we have reviewed when working on this. In fact, I also wondered if it's not too redundant, but in the end I concluded that it should be there, just for completeness.

Note, that Address type is sometimes used *outside* of the AbstractContact type, and we also allow developers to reuse this format in other projects (even outside EWP). You could probably deduce the value of recipientName in most contexts, but - in cases you could not (which is possible, I think) - this field might be useful. Also we don't force anyone to fill this out, so it shouldn't hurt.

**Comment by wrygiel** [comment]
One more argument (though, I admit, a bit far-fetched): It seems possible that some entities might want to be addressed a bit differently when their names are printed on envelopes.

**Comment by kaiqu** [comment]
> We don't have a "contact-name" in the address data type. We have one in AbstractContact though, so probably this is what you mean?

Yes.

> [...] In fact, I also wondered if it's not too redundant, but in the end I concluded that it should be there, just for completeness.
>
> Note, that Address type is sometimes used outside of the AbstractContact type, and we also allow developers to reuse this format in other projects (even outside EWP). You could probably deduce the value of recipientName in most contexts, but - in cases you could not (which is possible, I think) - this field might be useful. Also we don't force anyone to fill this out, so it shouldn't hurt.

Ok.
